### ISSUE TITLE
Pedos en ventas

### ISSUE THREAD

**Issue by Doncamatic1117** [Pedro-Nicolas-Rios-Vargas/Abarrotes-Valdivia#1]
Despues de cobrar y recibir el cambio, la venta no es guardada. (Curiosamente hay una venta de hoy 23/04/2020 de $0.0)

**Comment by Doncamatic1117** [comment]
*Actualización* El archivo que guarda las ventas se modificó sin agregar la venta hecha, eliminando una venta (pero eso ya se verá en gestión de ventas)

**Comment by VRVG1** [comment]
Master, me acabo de acordar que hay una version 1.4 que perdi xd

**Comment by Doncamatic1117** [comment]
> Master, me acabo de acordar que hay una version 1.4 que perdi xd

XD this hombre

**Comment by Doncamatic1117** [comment]
Ya no hay pedo, falsa alarma
