### ISSUE TITLE
Issue #2 Modificar en Gestionar Almacen 

### ISSUE THREAD

**Issue by Pedro-Nicolas-Rios-Vargas** [Pedro-Nicolas-Rios-Vargas/Abarrotes-Valdivia#3]
Al momento de modificar el precio del primer elemento de la tabla este no se modifica. @VRVG1 

**Antes de la modificación:**
![image](https://user-images.githubusercontent.com/36179716/117872811-ba7a8f00-b264-11eb-9801-89e63a74716f.png)

**Después de la modificación:**
![image](https://user-images.githubusercontent.com/36179716/117872720-a33ba180-b264-11eb-9f4b-07bacf6e3c55.png)

**Comment by VRVG1** [comment]
No se arregla si actualizas la tabla? Que por ejemplo busques el producto modificado.

**Comment by Pedro-Nicolas-Rios-Vargas** [comment]
Noup

**Comment by VRVG1** [comment]
Ya quedo
